# 08.13.2020
# Ungraded questions at the end of unit 5 exercises


# Question 1
# Create an array to store 3 boolean values entered in by the user. 
# Print out YES if all the values are true and NO if at least one value is false.
# Hint: Prompt the user to enter true or false, and accept those values using gets.
# Since gets will give us back a string (instead of the boolean values we want)
# use if statements to convert those strings to boolean values.
bools = []
acceptable_vals = ["true", "false"]

# accept user input
3.times do
    puts "Please enter either true or false"
    bool = gets.chomp.downcase
    # verify user input is correct
    until acceptable_vals.include?(bool)
        puts "You didn't enter true or false, please do that"
        bool = gets.chomp.downcase
    end
    if bool == "true"
        bool = true
    elsif bool == "false"
        bool = false
    end
    bools.push(bool)
end

if bools.all?
    puts "YES"
else
    puts "NO"
end


# Question 2
# Create an array to store the following words:
# firetruck, fire drill, fire hydrant, firefighter, fireproof, fire station, fire hose.
# Then write code that uses the array to print out truck, drill, hydrant, fighter, proof,
# station, hose without modifying the original array.
array = ["firetruck", "fire drill", "fire hydrant", "firefighter", "fireproof", "fire station", "fire hose"]
array.each do |word|
    puts word.split("fire")[-1].strip
end


# Question 3
# Create an array to store the amount of money spent on 4 people during the Holidays.
# Have the user enter in the amount spent on each person. Print the total spent on all the people.
# Total money spent should be displayed with a dollar sign, decimal point, and only 2 digits after the decimal.
amounts = []
4.times do
    puts "Please enter the amount you spent"
    money = gets.chomp.to_f
    amounts << money
end

# ensure total written to 2 decimal points
# https://ruby-doc.org/core-2.0.0/Kernel.html#method-i-sprintf
total = sprintf('%.2f', amounts.sum)
puts "Total spent: $#{total}"



# Question 4
# Create an array to store 5 random numbers (between 1 and 10, including both 1 and 10)
# generated by the computer. Print out the square of each of the elements in the array.
array = Array.new(5) { rand(1..10) }
puts array
puts array.map{|e| e ** 2}